# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Geschichte' do
pod "JTMaterialTransition", "~> 1.0"
pod "SAConfettiView"
pod "FlowingMenu", "~> 0.2.0"
end

